/* =========================================
   Project Data — content for all 6 detail pages
   Bilingual (en/zh)
   ========================================= */

const PROJECTS = {

  /* ============== LUCI AI ============== */
  "luci-ai": {
    slug: "luci-ai",
    index: "01",
    era: "25 — now",
    parent_en: "Part of memories.ai →",
    parent_zh: "memories.ai 旗下 →",
    parentSlug: "memories-ai",
    eyebrow_en: "AI PM · Product Design · 25.05—25.11 · San Francisco",
    eyebrow_zh: "AI 产品经理 · 产品设计 · 25.05—25.11 · 旧金山",
    title_en: ["LUCI", "AI"],
    title_zh: ["LUCI", "AI"],
    tagline_en: "Personal Memory Companion",
    tagline_zh: "个人记忆伴侣",
    desc_en: "Hardware & App Ecosystem within memories.ai — bridging physical capture with AI memory models. I defined market positioning, developed the \"Highlights\" core feature, led the US & EU Beta Interview Program, and refined the brand identity.",
    desc_zh: "memories.ai 旗下的硬件与应用生态 —— 连接物理感知与 AI 记忆模型。我负责市场定位、0–1 开发核心功能「Highlights」、主导美 & 欧 Beta 用户访谈，并优化品牌身份。",
    tags_en: ["AI PM", "Product Design", "Hardware + App", "Branding", "User Research", "Beta Program"],
    tags_zh: ["AI 产品经理", "产品设计", "硬件 + App", "品牌", "用户研究", "Beta 项目"],
    heroImg: { src: "images/projects/luci-ai/hero.jpg", label_en: "LUCI · Personal Memory Companion", label_zh: "LUCI · 个人记忆伴侣", sub_en: "Hardware identity", sub_zh: "硬件身份", tone: "mono" },
    meta: [
      { label_en: "Parent", label_zh: "母品牌", value_en: "memories.ai", value_zh: "memories.ai" },
      { label_en: "Duration", label_zh: "时间", value_en: "May — Nov 2025", value_zh: "2025.05 — 2025.11" },
      { label_en: "Scope", label_zh: "范围", value_en: "Hardware + App\nBrand + Research", value_zh: "硬件 + App\n品牌 + 研究" },
      { label_en: "Markets", label_zh: "市场", value_en: "US & EU Beta", value_zh: "美 & 欧 Beta" },
    ],
    nda: true,
    heroButtons: [
      { label_en: "Visit LUCI website", label_zh: "访问 LUCI 官网", url: "https://memories.ai/luci/", style: "dark" },
      { label_en: "🔗 View PDF", label_zh: "🔗 查看 PDF", url: "https://drive.google.com/file/d/18_K5bmIR97BymcdhGoAd8xp2d-SSofTa/view?usp=sharing", style: "ghost" }
    ],
    sections: [
      {
        type: "role-list",
        label_en: "01 — My Role",
        label_zh: "01 — 我的角色",
        title_en: "Four pillars of product ownership.",
        title_zh: "四根产品支柱，由我负责。",
        items_en: [
          "Defined LUCI AI's market positioning — \"Personal Memory Companion\" identity",
          "0–1 developed the \"Highlights\" core feature for the App — from concept to spec",
          "Headed the US & EU Beta Interview Program — delivering data-driven insights for the 0–1 product launch",
          "Defined core user scenarios (Daily Recap / To-do) to bridge hardware capability with AI memory models",
          "Strategically refined LUCI AI branding to align with \"Personal Memory Companion\" identity",
        ],
        items_zh: [
          "定义 LUCI AI 的市场定位 ——「个人记忆伴侣」身份",
          "0–1 开发 App 核心功能「Highlights」—— 从概念到规格全流程",
          "主导美 & 欧 Beta 用户访谈项目 —— 为 0–1 上线提供数据驱动的洞察",
          "定义核心用户场景（每日回顾 / 待办），打通硬件能力与 AI 记忆模型",
          "战略性优化 LUCI AI 品牌，使之与「个人记忆伴侣」定位对齐",
        ],
        ndaCard: {
          label_en: "Due to NDA",
          label_zh: "受 NDA 保护",
          body_en: "Process screens, internal feature flows, and proprietary product specs are under NDA. This page covers public brand outcomes, strategic decisions, and research methodology.",
          body_zh: "过程细节、内部功能流程与专有产品规格受 NDA 保护。本页仅展示公开的品牌成果、战略决策与研究方法。",
          shareLabel_en: "What I can share",
          shareLabel_zh: "可分享内容",
          shareBody_en: "Brand identity · Market positioning strategy · User scenario framework · Research methodology · Impact results",
          shareBody_zh: "品牌身份 · 市场定位策略 · 用户场景框架 · 研究方法 · 影响结果"
        }
      },
      {
        type: "cards-3",
        label_en: "02 — Core Features",
        label_zh: "02 — 核心功能",
        title_en: "Bridging hardware capability with AI memory models.",
        title_zh: "打通硬件能力与 AI 记忆模型。",
        cards: [
          { num_en: "Core Feature", num_zh: "核心功能", title_en: "Highlights", title_zh: "Highlights", body_en: "0–1 developed the \"Highlights\" feature — surfacing the most meaningful moments from LUCI's captured memories. Defined the feature concept, user flow, and interaction model that serves as the product's primary value delivery mechanism.", body_zh: "0–1 开发「Highlights」功能 —— 把 LUCI 捕捉到的记忆中最有意义的瞬间呈现出来。定义了功能概念、用户流和交互模型，这是产品最核心的价值递送机制。" },
          { num_en: "Core Feature", num_zh: "核心功能", title_en: "Daily Recap", title_zh: "每日回顾", body_en: "Defined the Daily Recap user scenario — an end-of-day summary that bridges hardware capture with the AI memory model. Designed the information hierarchy and conversational flow for daily memory reflection.", body_zh: "定义「每日回顾」用户场景 —— 一天结束的总结，把硬件采集与 AI 记忆模型连接起来。设计了信息架构与对话流，用于每日记忆回顾。" },
          { num_en: "Core Feature", num_zh: "核心功能", title_en: "To-do Integration", title_zh: "待办整合", body_en: "Defined the To-do user scenario — connecting memory capture to actionable items. Bridging LUCI's hardware capability with the AI's ability to extract tasks from captured context.", body_zh: "定义「待办」用户场景 —— 把记忆捕捉与可执行事项连接起来。打通 LUCI 的硬件能力与 AI 从上下文中提取任务的能力。" },
        ],
      },
      {
        type: "scenarios",
        bg: "mist",
        label_en: "03 — User Scenarios",
        label_zh: "03 — 用户场景",
        title_en: "Three scenarios. One continuous loop of memory and action.",
        title_zh: "三个场景，一个持续运转的「记忆 → 行动」回环。",
        items: [
          { num: "01", title_en: "Daily Recap",         title_zh: "每日回顾",   body_en: "End-of-day AI summary of what LUCI captured. Transforms raw memory data into a meaningful narrative — helping users understand their day from the perspective of what they actually experienced.", body_zh: "一天结束时由 AI 总结 LUCI 所记录的内容。把原始记忆数据转化为有意义的叙事 —— 帮用户从「真正经历的事」的视角理解自己的一天。", tags_en: ["Memory Synthesis", "Daily Cadence"], tags_zh: ["记忆合成", "每日节奏"] },
          { num: "02", title_en: "Highlights",          title_zh: "Highlights", body_en: "Algorithmically surfaced significant moments across time. The \"Highlights\" feature I developed 0–1 — using AI to identify which memories are most worth preserving and revisiting.", body_zh: "用算法浮现跨时间的重要时刻。我 0–1 开发的「Highlights」功能 —— 由 AI 判断哪些记忆最值得保留与回看。", tags_en: ["AI Curation", "Core Feature"], tags_zh: ["AI 策展", "核心功能"] },
          { num: "03", title_en: "To-do from Memory",   title_zh: "记忆生待办", body_en: "AI extracts actionable items from captured context — bridging the passive memory capture of the hardware with the active task management needs of the user.", body_zh: "AI 从采集到的上下文中提取可执行事项 —— 把硬件被动记录与用户主动管理任务的需求连接起来。", tags_en: ["Action Extraction", "Productivity"], tags_zh: ["行动提取", "生产力"] },
          { num: "★", title_en: "Beta Research — US & EU", title_zh: "Beta 调研 — 美 & 欧", body_en: "Headed the Beta Interview Program across US and EU markets. Synthesised qualitative insights into product decisions — data-driven inputs for the 0–1 launch strategy.", body_zh: "主导美国与欧洲两地的 Beta 用户访谈项目。把质性洞察提炼为产品决策 —— 为 0–1 上线策略提供数据输入。", tags_en: ["User Research", "Beta Programme", "US · EU"], tags_zh: ["用户研究", "Beta 项目", "美 · 欧"] },
        ],
      },
      {
        type: "brand-band",
        label_en: "04 — Brand Identity",
        label_zh: "04 — 品牌身份",
        wordmark_en: ["LUCI", "AI"],
        wordmark_zh: ["LUCI", "AI"],
        sub_en: "Personal Memory Companion",
        sub_zh: "个人记忆伴侣",
        desc_en: "Strategically refined LUCI AI's branding to align with its \"Personal Memory Companion\" positioning. The brand needed to feel intimate, trustworthy, and premium — fitting within the memories.ai ecosystem while carving its own identity as a hardware product.",
        desc_zh: "战略性优化 LUCI AI 的品牌，使之贴合「个人记忆伴侣」的定位。品牌要让人感到亲近、可信、有质感 —— 既属于 memories.ai 生态，又作为一个硬件产品有独立的身份。",
        attrs_en: ["Intimate", "Trustworthy", "Premium", "Personal", "Continuous"],
        attrs_zh: ["亲近", "可信", "有质感", "私人", "持续"],
      },
    ],
    stats: [
      { num: "0→1", label_en: "Highlights feature\ndeveloped end-to-end", label_zh: "Highlights 功能\n端到端开发" },
      { num_en: "US + EU", num_zh: "美 + 欧", label_en: "Beta interview markets",     label_zh: "Beta 访谈市场" },
      { num: "3",   label_en: "Core user scenarios\ndefined & specced", label_zh: "三个核心用户场景\n定义并产出规格" },
      { num: "1",   label_en: "Brand identity\naligned & refined",     label_zh: "品牌身份\n对齐并打磨" },
    ],
    nextSlug: "memories-ai",
  },

  /* ============== memories.ai ============== */
  "memories-ai": {
    slug: "memories-ai",
    index: "02",
    era: "25.05 — 25.11",
    eyebrow_en: "Product Manager · Creative Designer · 25.05—25.11 · San Francisco",
    eyebrow_zh: "产品经理 · 创意设计师 · 25.05—25.11 · 旧金山",
    title_en: ["memories", ".ai"],
    title_zh: ["memories", ".ai"],
    tagline_en: "World's first Large Visual-Memory Model.",
    tagline_zh: "全球首个大型视觉记忆模型。",
    desc_en: "Introducing the world's first Large Visual-Memory Model. Two product lines: the LVMM platform and the LUCI AI hardware & app ecosystem.",
    desc_zh: "推出全球首个大型视觉记忆模型。两条产品线：LVMM 平台和 LUCI AI 硬件 & 应用生态。",
    tags_en: ["AI PM", "Creative Direction", "Brand & CIS", "Web Design", "Video Agents", "LVMM"],
    tags_zh: ["AI 产品经理", "创意指导", "品牌 & CIS", "网页设计", "视频 Agent", "LVMM"],
    heroImg: { label_en: "memories.ai · LVMM", label_zh: "memories.ai · LVMM", sub_en: "Brand & website system", sub_zh: "品牌与网站系统", tone: "mono-blue" },
    meta: [
      { label_en: "Role",     label_zh: "角色",   value_en: "Product Manager\nCreative Designer", value_zh: "产品经理\n创意设计师" },
      { label_en: "Duration", label_zh: "时间",   value_en: "May — Nov 2025\nFull-time",          value_zh: "2025.05 — 11\n全职" },
      { label_en: "Location", label_zh: "地点",   value_en: "San Francisco Bay Area, US",         value_zh: "美国 旧金山湾区" },
      { label_en: "Products", label_zh: "产品",   value_en: "LVMM · AI Video Agents\nLUCI AI Hardware + App", value_zh: "LVMM · 视频 Agent\nLUCI AI 硬件 + App" },
    ],
    nda: true,
    sections: [
      {
        type: "role-list",
        bg: "ink",
        label_en: "01 — Product Line 1 · LVMM",
        label_zh: "01 — 产品线 1 · LVMM",
        title_en: "Large Visual-Memory Model — 0→1 brand and platform.",
        title_zh: "大型视觉记忆模型 —— 0→1 的品牌与平台。",
        intro_en: "memories.ai is introducing the world's first LVMM — a model that sees, remembers and acts. My role spanned brand identity, information architecture, website design, and AI product development across both product lines.",
        intro_zh: "memories.ai 正在推出全球首个 LVMM —— 一个会看、会记住、会行动的模型。我的工作跨越品牌、信息架构、网页设计与 AI 产品开发，覆盖两条产品线。",
        items_en: [
          "0–1 spearheaded the branding and CIS system — cohesive global visual identity from scratch.",
          "0–1 led IA and co-designed the official website, transforming complex LVMM narratives into high-fidelity UI.",
          "Architected and 0–1 developed AI Video Agents (Video Editor / Marketer), optimising UX for prosumers.",
          "Directed and designed the product launch video — 2M+ views through expert creative direction.",
        ],
        items_zh: [
          "0–1 主导品牌与 CIS 系统建设 —— 从零搭建统一的全球视觉识别。",
          "0–1 负责信息架构、共同设计官网，把复杂的 LVMM 叙事转化为高保真 UI。",
          "0–1 架构并开发 AI Video Agents（视频编辑 / 营销），为进阶用户优化体验。",
          "执导并设计产品发布视频 —— 凭借专业的创意指导达成 200 万+ 播放。",
        ],
      },
      {
        type: "cards-4",
        label_en: "02 — AI Video Agents",
        label_zh: "02 — AI 视频 Agent",
        title_en: "Video Editor + Video Marketer agents, built for prosumers.",
        title_zh: "为进阶用户打造的视频编辑 + 视频营销 Agent。",
        cards: [
          { num_en: "Architecture",      num_zh: "架构",       title_en: "0→1 Agent Design",       title_zh: "0→1 Agent 设计",     body_en: "Architected the full UX flow for two AI Video Agents: an editing agent and a marketing agent — from user brief to rendered output.", body_zh: "为两个 AI 视频 Agent 架构完整的 UX 流程：编辑 Agent 与营销 Agent —— 从用户简报到成品输出。" },
          { num_en: "User Research",     num_zh: "用户研究",   title_en: "Prosumer Focus",         title_zh: "聚焦进阶用户",       body_en: "Optimised UX specifically for prosumers — content creators who need professional-quality output with consumer-grade simplicity.", body_zh: "针对进阶用户专门优化 UX —— 需要专业级产出，但又要消费级使用门槛的内容创作者。" },
          { num_en: "Creative Direction", num_zh: "创意指导",  title_en: "Launch Video",           title_zh: "发布视频",           body_en: "Directed and designed the product launch video from script through post-production. Result: 2M+ views on launch.", body_zh: "执导并设计产品发布视频，从脚本到后期一手负责。结果：上线即 200 万+ 播放。" },
          { num_en: "Impact",            num_zh: "结果",       title_en: "2M+ Views",              title_zh: "200 万+ 播放",      body_en: "The launch video achieved 2 million+ views — validating the creative direction strategy and product positioning.", body_zh: "发布视频达成 200 万+ 播放 —— 验证了创意方向与产品定位策略。" },
        ],
      },
      {
        type: "role-list",
        label_en: "03 — Product Line 2 · LUCI AI",
        label_zh: "03 — 产品线 2 · LUCI AI",
        title_en: "Hardware & App Ecosystem — Personal Memory Companion.",
        title_zh: "硬件 & 应用生态 —— 个人记忆伴侣。",
        intro_en: "LUCI AI is a hardware-meets-app product sitting within the memories.ai ecosystem. My scope covered market positioning, core feature development, beta interview programme, and branding refinement.",
        intro_zh: "LUCI AI 是 memories.ai 生态中的「硬件 × 应用」产品。我的工作覆盖市场定位、核心功能开发、Beta 用户访谈项目，以及品牌优化。",
        items_en: [
          "Defined LUCI AI's market positioning and 0–1 developed the \"Highlights\" core feature for the App.",
          "Headed the US & EU Beta Interview Program — data-driven insights for the 0–1 product launch.",
          "Defined core user scenarios (Daily Recap / To-do) to bridge hardware capability with AI memory models.",
          "Strategically refined LUCI AI branding to align with its \"Personal Memory Companion\" identity.",
        ],
        items_zh: [
          "定义 LUCI AI 的市场定位，并 0–1 开发 App 核心功能「Highlights」。",
          "主导美 & 欧 Beta 用户访谈项目 —— 为 0–1 上线提供数据驱动的洞察。",
          "定义核心用户场景（每日回顾 / 待办），打通硬件能力与 AI 记忆模型。",
          "战略性优化 LUCI AI 品牌，使之与「个人记忆伴侣」定位对齐。",
        ],
        cta_en: "View LUCI AI →",
        cta_zh: "查看 LUCI AI →",
        ctaSlug: "luci-ai",
      },
    ],
    stats: [
      { num: "2M+",     label_en: "Launch video views",            label_zh: "发布视频播放" },
      { num: "0→1",     label_en: "Brand · Web · Agents\nLUCI core feature", label_zh: "品牌 · 官网 · Agent\nLUCI 核心功能" },
      { num_en: "US + EU", num_zh: "美 + 欧", label_en: "Beta interview programme", label_zh: "Beta 访谈项目" },
      { num_en: "6 mo", num_zh: "6 月", label_en: "Full-time · SF Bay Area",      label_zh: "全职 · 旧金山湾区" },
    ],
    nextSlug: "mincho-ai",
  },

  /* ============== Mincho AI ============== */
  "mincho-ai": {
    slug: "mincho-ai",
    index: "03",
    era: "25.01 — 25.04",
    eyebrow_en: "AI PM · UX Design · 25.01—25.04 · Shanghai",
    eyebrow_zh: "AI 产品经理 · 体验设计 · 25.01—25.04 · 上海",
    title_en: ["Mincho", "AI"],
    title_zh: ["Mincho", "AI"],
    tagline_en: "AI for mental healing — 300+ specialised agents.",
    tagline_zh: "为心理疗愈而生的 AI —— 300+ 专业 Agent。",
    desc_en: "A WeChat Mini Program for mental healing — 300+ specialised AI agents, powered by Xinyun AI, officially launched 15 April 2025.",
    desc_zh: "面向心理疗愈的微信小程序 —— 300+ 专业 AI Agent，由「心韵」基模驱动，已于 2025 年 4 月 15 日正式上线 Beta。",
    tags_en: ["AI PM", "UX Design", "WeChat Mini Program", "Mental Healing", "Branding"],
    tags_zh: ["AI 产品经理", "体验设计", "微信小程序", "心理疗愈", "品牌"],
    heroImg: { label_en: "Mincho · Beta", label_zh: "Mincho · Beta", sub_en: "Conversational mental healing", sub_zh: "对话式心理疗愈", tone: "steel" },
    meta: [
      { label_en: "Role",     label_zh: "角色",   value_en: "AI Product Manager\nUX Designer", value_zh: "AI 产品经理\n体验设计师" },
      { label_en: "Duration", label_zh: "时间",   value_en: "Jan — Apr 2025\nContract",        value_zh: "2025.01 — 04\n合约" },
      { label_en: "Company",  label_zh: "公司",   value_en: "Mincho AI\nShanghai, China",      value_zh: "Mincho AI\n中国 上海" },
      { label_en: "Platform", label_zh: "平台",   value_en: "WeChat Mini Program\nXinyun AI foundation", value_zh: "微信小程序\n「心韵」基模" },
    ],
    sections: [
      {
        type: "role-list",
        label_en: "01 — The Product",
        label_zh: "01 — 产品",
        title_en: "Psychology-focused AI platform with 300+ specialised agents.",
        title_zh: "以心理学为基底，集合 300+ 专业 AI Agent 的平台。",
        intro_en: "Mincho is a WeChat Mini Program powered by Xinyun AI's proprietary foundation model. It brings together 300+ specialised AI agents designed to support diverse mental health and emotional wellbeing needs — one of the most comprehensive and systematic therapeutic AI platforms to date. My role: led the 0–1 product architecture, UX design, AI agent testing, and brand strategy from January through to the April 2025 beta launch.",
        intro_zh: "Mincho 是一款微信小程序，由心韵 AI 自研基模驱动，集合 300+ 专业 AI Agent，覆盖多元的心理健康与情绪疗愈需求 —— 是目前最系统的疗愈型 AI 平台之一。我的角色：从 1 月到 4 月 Beta 上线，主导 0–1 产品架构、体验设计、AI Agent 测试与品牌策略。",
        items_en: [
          "Led feature architecture and 0–1 development of Mincho AI beta mini-program.",
          "Designed and optimised UX to improve user retention.",
          "Tested 500+ AI agents, fine-tuned prompts — boosting accuracy by 13%.",
          "Built Mincho AI's branding and market strategy.",
        ],
        items_zh: [
          "主导功能架构与 Mincho AI Beta 小程序的 0–1 开发。",
          "设计并优化用户体验，提升留存。",
          "测试 500+ AI Agent，微调提示词 —— 准确率提升 13%。",
          "搭建 Mincho AI 的品牌与市场策略。",
        ],
      },
      {
        type: "cards-3",
        bg: "mist",
        label_en: "02 — Feature Architecture",
        label_zh: "02 — 功能架构",
        title_en: "0→1. From blank product to beta launch in 4 months.",
        title_zh: "0→1。四个月，从一张白纸到 Beta 上线。",
        cards: [
          { num_en: "Product Architecture", num_zh: "产品架构",   title_en: "Feature Architecture & Mini Program", title_zh: "功能架构 & 小程序", body_en: "Led 0–1 feature architecture of the WeChat Mini Program. Defined information architecture, core user flows, and conversational UX patterns for a therapy-oriented AI product. Collaborated with engineers throughout the build cycle.", body_zh: "主导微信小程序的 0–1 功能架构。为一款疗愈方向的 AI 产品，定义信息架构、核心用户流与对话式 UX 模式。整个开发周期与工程师紧密协作。" },
          { num_en: "AI Agent Engineering", num_zh: "AI 工程",   title_en: "500+ Agents · 13% Accuracy Boost",    title_zh: "500+ Agent · 准确率 +13%", body_en: "Tested over 500 AI agents powered by the Xinyun AI foundation model. Fine-tuned prompts systematically across mental health domains — anxiety, depression support, emotional regulation — boosting overall agent accuracy by 13%.", body_zh: "测试 500+ 由心韵基模驱动的 AI Agent。在焦虑、抑郁支持、情绪调节等多个心理领域系统性微调提示词 —— 整体准确率提升 13%。" },
          { num_en: "Brand & Strategy",     num_zh: "品牌 & 策略", title_en: "Branding + Market Strategy",          title_zh: "品牌 + 市场策略",   body_en: "Built Mincho AI's complete branding system and market strategy. Defined brand personality (\"warm, empathetic, safe\"), visual identity, tone of voice, and go-to-market approach for the China mental health app space.", body_zh: "搭建完整的 Mincho AI 品牌系统与市场策略。定义品牌个性（「温暖、共情、安全」）、视觉识别、语调与中国心理健康赛道的上市策略。" },
        ],
      },
      {
        type: "intro-block",
        label_en: "03 — Beta Launch",
        label_zh: "03 — Beta 上线",
        title_en: "Officially launched 15 April 2025.",
        title_zh: "2025 年 4 月 15 日正式上线。",
        body_en: "Mincho Beta opened to users April 15, 2025. The platform is currently free — inviting users to explore a meaningful, AI-driven mental wellness experience. The beta launch video was directed and produced during the product development phase.",
        body_zh: "Mincho Beta 于 2025 年 4 月 15 日向用户开放。目前所有功能免费，欢迎用户来探索一种有意义的、AI 驱动的心理健康体验。Beta 发布视频也在开发期同步执导与制作。",
        quote_en: "Platform: WeChat Mini Program · Currently in open beta · All features free. Foundation model: Xinyun AI · 300+ specialised agents.",
        quote_zh: "平台：微信小程序 · 当前公开 Beta · 全功能免费。基模：心韵 AI · 300+ 专业 Agent。",
      },
    ],
    stats: [
      { num: "300+",  label_en: "Specialised AI agents", label_zh: "专业 AI Agent" },
      { num: "500+",  label_en: "AI agents tested",      label_zh: "测试过的 AI Agent" },
      { num: "+13%",  label_en: "Accuracy improvement",  label_zh: "准确率提升" },
      { num_en: "4 mo", num_zh: "4 月", label_en: "0 → Beta launch", label_zh: "0 → Beta 上线" },
    ],
    nextSlug: "emosync",
  },

  /* ============== EmoSync ============== */
  "emosync": {
    slug: "emosync",
    index: "04",
    era: "23.09 — 24.08",
    eyebrow_en: "GSA MDes · Design Innovation & Interaction Design · 23—24",
    eyebrow_zh: "GSA MDes · 设计创新 & 交互设计 · 23—24",
    title_en: ["Emo", "Sync"],
    title_zh: ["Emo", "Sync"],
    tagline_en: "The Embodied Emotion Guide.",
    tagline_zh: "身体引导的情绪指南。",
    desc_en: "Exploring embodied interaction therapy design for emotional healing in youths — integrating interactive games and creative therapies to educate young people about the connection between body postures and emotions.",
    desc_zh: "探索身体交互式的情绪疗愈设计，面向青少年 —— 把交互游戏与创意疗法结合在一起，让年轻人理解身体姿态与情绪之间的连接。",
    tags_en: ["Creative Therapy", "Body & Mind", "Interaction Game", "Young People", "Emotional Health", "Mediapipe"],
    tags_zh: ["创意疗法", "身心连接", "交互游戏", "青年人群", "情绪健康", "Mediapipe"],
    heroImg: { label_en: "EmoSync · Toolbox 2024", label_zh: "EmoSync · 工具盒 2024", sub_en: "Acrylic body puzzle", sub_zh: "亚克力身体拼图", tone: "mono-mist" },
    meta: [
      { label_en: "Full title", label_zh: "全名",    value_en: "EmoSync: The Embodied Emotion Guide", value_zh: "EmoSync：身体引导的情绪指南" },
      { label_en: "Focus",      label_zh: "聚焦",    value_en: "Improving emotional distress in youths through embodied interaction", value_zh: "通过身体交互改善青少年的情绪困扰" },
      { label_en: "Degree",     label_zh: "学位",    value_en: "Cheng Zheng · MDes Design Innovation & Interaction Design, GSA", value_zh: "郑诚 · GSA MDes 设计创新 & 交互设计" },
      { label_en: "Duration",   label_zh: "时间",    value_en: "23.09 — 24.08 · Individual thesis project", value_zh: "23.09 — 24.08 · 毕业论文（个人项目）" },
    ],
    sections: [
      {
        type: "intro-block",
        bg: "mist",
        label_en: "01 — The Project",
        label_zh: "01 — 项目",
        title_en: "Creative therapy · Body & Mind · Interaction Game · Young People.",
        title_zh: "创意疗法 · 身心连接 · 交互游戏 · 青少年。",
        body_en: "EmoSync explores embodied interaction therapy design for emotional healing, focusing on improving youths' emotional distress by integrating interactive games and creative therapies. Entry point: early research on schizophrenia (1 in 222 young adults affected worldwide; diagnosis typically age 16–25). Pivoted to the final focus: emotional distress in youths — a broader, more accessible intervention space. Design process: Empathise → Define → Experiment → Ideate → Prototype → Deliver.",
        body_zh: "EmoSync 探索面向情绪疗愈的身体交互疗法设计，专注于通过交互游戏与创意疗法改善青少年的情绪困扰。切入点：早期关于精神分裂症的研究（全球每 222 名年轻人中就有 1 人受影响；通常发病于 16–25 岁）。最终聚焦：青少年的情绪困扰 —— 一个更广泛、更易触达的干预空间。设计过程：共情 → 定义 → 实验 → 概念 → 原型 → 交付。",
        quote_en: "How might we design an embodied interaction intervention that helps young people understand and regulate their emotions through body movement and creativity?",
        quote_zh: "我们能否设计一个身体交互式的干预方式，让年轻人通过身体运动与创造力来理解与调节自己的情绪？",
      },
      {
        type: "timeline",
        label_en: "02 — Research Process",
        label_zh: "02 — 研究过程",
        title_en: "From schizophrenia to emotional distress in youths.",
        title_zh: "从精神分裂研究，回到青少年情绪困扰。",
        items: [
          { phase_en: "Empathise",  phase_zh: "共情",   title_en: "Entry Point: Schizophrenia Research", title_zh: "切入点：精神分裂研究",      body_en: "1 in 222 young adults affected worldwide. Early intervention significantly improves outcomes. Researched psychotherapy approaches: CBT, Group Therapy, Family Therapy, Social Skills Training.", body_zh: "全球每 222 名年轻人中即有 1 人受影响。早期介入能显著改善结果。研究多种心理治疗方法：CBT、团体治疗、家庭治疗、社交技能训练。" },
          { phase_en: "Define",     phase_zh: "定义",   title_en: "Final Focus: Emotional Distress in Youths", title_zh: "最终聚焦：青少年情绪困扰", body_en: "Interview 01 thematic analysis: Routine & Environment · Social Interaction · Emotional Trigger & Overthink · Physical Sensation · Personal Differences · Emotional Regulation · Lack of Perception. Key finding: strong connection between body and mind; difficulty identifying and expressing emotions.", body_zh: "第一轮访谈主题分析：作息与环境 · 社交互动 · 情绪触发与过度思考 · 身体感觉 · 个体差异 · 情绪调节 · 缺乏觉察。关键发现：身心连接强；识别与表达情绪困难。" },
          { phase_en: "Participatory", phase_zh: "参与式研究", title_en: "Innerspace Online Event + CBT Therapist Interview", title_zh: "Innerspace 线上活动 + CBT 治疗师访谈", body_en: "Attended the Innerspace \"Embracing All Your Emotions\" online event. CBT therapist emphasised mindfulness — leading to exploring mindful acceptance for emotional wellbeing. Two key insights: acceptance of negative emotions; effectiveness of mindfulness meditation in emotional release.", body_zh: "参加 Innerspace「拥抱你的所有情绪」线上活动。CBT 治疗师强调正念 —— 促使我探索「正念式接纳」作为情绪健康的方法。两个关键洞察：接纳负面情绪；正念冥想对情绪释放的有效性。" },
          { phase_en: "Ideate",     phase_zh: "概念",   title_en: "Inspirations & Concept Ideas", title_zh: "灵感与概念",                body_en: "References: Sony Wow Studio, SlowMo Therapy, Art Therapy with Nature, Tactum Skin-Centric Design. Ideas: Body Interactive Game, Emotion Colour Interaction, Art Therapy Workshop, Mindfulness Reminder Device.", body_zh: "参考案例：索尼 Wow Studio、SlowMo Therapy、自然艺术疗法、Tactum 皮肤中心设计。概念：身体交互游戏、情绪色彩交互、艺术疗法工作坊、正念提醒装置。" },
          { phase_en: "Prototype",  phase_zh: "原型",   title_en: "From Sketches to Laser-Cut Acrylic", title_zh: "从草图到激光切割亚克力",   body_en: "Sketched body-puzzle concept → 3D render of mannequin + circular base → laser cutting at GSA workshop. Components: acrylic body skeleton pieces, circular tray, puzzle pieces, connecting rings. Multiple fabrication iterations.", body_zh: "草拟身体拼图概念 → 3D 渲染人偶 + 圆形底座 → 在 GSA 工坊激光切割。组件：亚克力骨架块、圆形托盘、拼图块、连接环。多轮制造迭代。" },
        ],
      },
      {
        type: "cards-3",
        label_en: "03 — The Outcome",
        label_zh: "03 — 成果",
        title_en: "Three components. One circular toolbox.",
        title_zh: "三个组件，一个圆形工具盒。",
        intro_en: "EmoSync is a creative therapeutic toolbox for users to explore the link between body postures and emotions — promoting emotional health and body creativity. Potential service for NHS, art therapy groups, wellbeing charities, spiritual communities, and individual users.",
        intro_zh: "EmoSync 是一个创意疗愈工具盒，让用户探索身体姿态与情绪之间的连接 —— 促进情绪健康和身体创造力。可服务于 NHS、艺术治疗团体、健康慈善组织、灵性社群与个人用户。",
        cards: [
          { num_en: "01 · Guidebook",       num_zh: "01 · 指南手册", title_en: "Guidebook",            title_zh: "指南手册",    body_en: "How to use EmoSync. Educates users on embodied knowledge of body postures and emotions. Introduces the connection between physical movement and emotional states through illustrated content.", body_zh: "如何使用 EmoSync。带用户进入身体姿态与情绪的具身认知。通过插图内容介绍身体动作与情绪状态之间的连接。" },
          { num_en: "02 · Physical Puzzle", num_zh: "02 · 实体拼图", title_en: "Physical Body Puzzle", title_zh: "身体实体拼图", body_en: "Laser-cut acrylic body skeleton pieces. Colour, play and display — a tactile object for exploring body configurations. Assembling the puzzle creates body postures that correspond to different emotional states.", body_zh: "激光切割的亚克力骨架块。可上色、可游戏、可展示 —— 一个可触摸的物件，用来探索身体造型。拼装出的姿态对应不同的情绪状态。" },
          { num_en: "03 · Website",         num_zh: "03 · 网站",     title_en: "emosync.co.uk",        title_zh: "emosync.co.uk", body_en: "3D mannequin (Tilt / Turn / Move X/Y/Z) with Emotional Colour Picker. Body tracking games: ManneMotion and EmoColour (Mediapipe body-data game generating emotional colour patterns from limb movements).", body_zh: "3D 人偶（倾斜 / 旋转 / X·Y·Z 移动）+ 情绪色彩选择器。身体追踪游戏：ManneMotion 与 EmoColour（基于 Mediapipe 身体数据，由肢体动作生成情绪色彩图案）。" },
        ],
      },
    ],
    stats: [
      { num: "45",  label_en: "Page process document\nFull research journey",     label_zh: "45 页过程文档\n完整研究旅程" },
      { num: "7",   label_en: "Stakeholder organisations\nNHS · Findhorn · GSA…", label_zh: "7 家利益相关方\nNHS · Findhorn · GSA…" },
      { num: "3",   label_en: "Toolbox components\nGuidebook · Puzzle · Website", label_zh: "3 个工具盒组件\n手册 · 拼图 · 网站" },
      { num: "2",   label_en: "Interactive games\nManneMotion · EmoColour",       label_zh: "2 个交互游戏\nManneMotion · EmoColour" },
    ],
    nextSlug: "nature-times",
  },

  /* ============== Nature Times ============== */
  "nature-times": {
    slug: "nature-times",
    index: "05",
    era: "24.02 — 24.05",
    eyebrow_en: "GSA × N4H · Citizen Science Project · 24.02—24.05",
    eyebrow_zh: "GSA × N4H · 公民科学项目 · 24.02—24.05",
    title_en: ["Nature", "Times"],
    title_zh: ["Nature", "Times"],
    tagline_en: "Citizen science kit for high school students in Lossiemouth.",
    tagline_zh: "为 Lossiemouth 高中生设计的公民科学工具包。",
    desc_en: "A multi-sensory citizen science kit connecting Lossiemouth high school students to phenology data collection and nature therapy — in collaboration with N4H (Nature for Health).",
    desc_zh: "一个多感官的公民科学工具包，把 Lossiemouth 的高中生与物候学数据采集、自然疗法连接起来 —— 与 N4H（Nature for Health）合作开发。",
    tags_en: ["Citizen Science", "Phenology", "Co-design", "Eco-printing", "Experience Design"],
    tags_zh: ["公民科学", "物候学", "共创设计", "生态拓印", "体验设计"],
    heroImg: { label_en: "Nature Times · Kit 2024", label_zh: "Nature Times · 工具盒 2024", sub_en: "Yellow toolbox on grass", sub_zh: "草地上的黄色工具盒", tone: "mono" },
    meta: [
      { label_en: "Role",     label_zh: "角色",   value_en: "Experience Designer\nPublication Designer", value_zh: "体验设计师\n出版物设计师" },
      { label_en: "Duration", label_zh: "时间",   value_en: "24.02 — 24.05\nGroup 7, GSA MDes",        value_zh: "24.02 — 24.05\nGSA MDes 第 7 组" },
      { label_en: "Partner",  label_zh: "合作方", value_en: "N4H (Nature for Health)\nRuaraidh Milne & Stephen Wiseman", value_zh: "N4H（Nature for Health）\nRuaraidh Milne & Stephen Wiseman" },
      { label_en: "School",   label_zh: "学校",   value_en: "Lossiemouth High School\nS1 students, Scotland", value_zh: "Lossiemouth 高中\nS1 学生，苏格兰" },
    ],
    sections: [
      {
        type: "intro-block",
        bg: "mist",
        label_en: "01 — Context",
        label_zh: "01 — 背景",
        title_en: "Bridging N4H and young people through citizen science.",
        title_zh: "用公民科学，连接 N4H 与年轻人。",
        body_en: "The project aimed to co-design a citizen science intervention with and for Scottish high school students, in collaboration with N4H — an organisation dedicated to promoting nature's benefits for mental wellbeing. N4H's co-founders Ruaraidh Milne and Stephen Wiseman run Nature Walks for Wellbeing, Branching Out (NHS-developed, for adults using mental health services), and Training programs. Our team's role: bridge N4H and Lossiemouth S1 students to collect meaningful phenology data together.",
        body_zh: "项目目标：与苏格兰高中生共创一项公民科学介入方案，合作方为 N4H —— 一家致力于推广「自然对心理健康益处」的组织。N4H 联合创始人 Ruaraidh Milne 与 Stephen Wiseman 经营 Nature Walks for Wellbeing、Branching Out（与 NHS 共同开发，面向使用心理健康服务的成年人），以及培训项目。我们的角色：把 N4H 和 Lossiemouth 的 S1 学生连接起来，一起采集有意义的物候学数据。",
        quote_en: "How do you make seasonal data collection feel like an adventure — not homework?",
        quote_zh: "怎样让「季节性数据采集」感觉像一场冒险 —— 而不是家庭作业？",
      },
      {
        type: "cards-3",
        label_en: "02 — Design Process",
        label_zh: "02 — 设计过程",
        title_en: "Co-design with students. Three sensory activities. One kit.",
        title_zh: "与学生共创。三种感官活动，集合于一个工具包。",
        cards: [
          { num_en: "01 · Co-design",  num_zh: "01 · 共创",      title_en: "Co-design Session",    title_zh: "共创工作坊",       body_en: "Ran a co-design workshop with Lossiemouth S1 students. Students shaped the kit's activities and defined what \"playful nature\" meant to them. Their request: collect data individually, upload it, and learn from comparisons.", body_zh: "与 Lossiemouth S1 学生一起开展共创工作坊。由学生自己塑造工具包的活动、定义「好玩的自然」对他们意味着什么。他们的诉求：单独采集、上传、对比学习。" },
          { num_en: "02 · Kit Build",  num_zh: "02 · 工具盒",    title_en: "Three Sensory Activities", title_zh: "三种感官活动",   body_en: "Three opportunities → three activities: Soundscape (Arduino thermal printer + microphone), Timelapse (Arduino ArduCam 5MP + Data Recorder Shield with RTC), and Eco-printing (natural dye imprinting from leaves and plants).", body_zh: "三个设计机会变成三种活动：声音景观（Arduino 热敏打印机 + 麦克风）、延时摄影（Arduino ArduCam 5MP + 带 RTC 的数据记录板）、生态拓印（用叶片与植物做天然染料拓印）。" },
          { num_en: "03 · Website",    num_zh: "03 · 网站",      title_en: "Nature Times Website", title_zh: "Nature Times 网站", body_en: "Homepage with Plants/Birds of the Day, Upload page, Recognized Species page, Database. Timelapse feature had ArduCam issues — we created a process video for user testing alongside the eco-printing guideline.", body_zh: "首页有「今日植物 / 鸟类」、上传页、识别物种页、数据库。延时摄影部分遇到 ArduCam 问题 —— 我们做了过程视频用于用户测试，并附上生态拓印指南。" },
        ],
      },
      {
        type: "user-journey",
        bg: "mist",
        label_en: "03 — User Journey",
        label_zh: "03 — 用户旅程",
        title_en: "School → Nature → Home.",
        title_zh: "学校 → 自然 → 家。",
        stages: [
          {
            stage_en: "School",  stage_zh: "学校",
            items_en: ["Get kit from school.", "Learn how to use the kit.", "Discuss in class."],
            items_zh: ["在学校领取工具盒。", "学习如何使用。", "在课堂上讨论。"],
            adds: [],
          },
          {
            stage_en: "Nature",  stage_zh: "自然",
            items_en: ["Go to nature / walk.", "Nature walk activity.", "Collect phenology data."],
            items_zh: ["走入自然 / 散步。", "自然行走活动。", "采集物候学数据。"],
            addItems_en: ["Collect data individually ★"],
            addItems_zh: ["单独采集数据 ★"],
          },
          {
            stage_en: "Home",    stage_zh: "家",
            items_en: ["Make music / eco-print / postcard."],
            items_zh: ["做音乐 / 生态拓印 / 明信片。"],
            addItems_en: ["Upload data to website ★", "Learn from comparison ★", "Display what was collected."],
            addItems_zh: ["上传数据到网站 ★", "通过对比学习 ★", "展示自己采集的东西。"],
          },
        ],
        note_en: "★ = added by students in the co-design session.",
        note_zh: "★ = 共创工作坊中由学生自己提出新增。",
      },
    ],
    stats: [
      { num: "3",  label_en: "Design opportunities\nSoundscape · Timelapse · Eco-print", label_zh: "3 个设计机会\n声音 · 延时 · 拓印" },
      { num: "3",  label_en: "Stakeholder types\nN4H · Teachers · S1 Students",          label_zh: "3 类利益相关方\nN4H · 教师 · S1 学生" },
      { num: "31", label_en: "Team slides\n+ 28-page personal journal",                  label_zh: "团队 31 页 + 个人日志 28 页" },
      { num: "GSA", label_en: "Exhibited · Degree Show 2024\nHaldane Building, Glasgow",  label_zh: "GSA Degree Show 2024 展出\nHaldane Building, Glasgow" },
    ],
    nextSlug: "archive-21-23",
  },

  /* ============== Archive 21–23 ============== */
  "archive-21-23": {
    slug: "archive-21-23",
    index: "06",
    era: "21 — 23",
    eyebrow_en: "Archive · 21—23 · Shaping Portfolio",
    eyebrow_zh: "存档 · 21—23 · 塑造作品集",
    title_en: ["Before", "AI"],
    title_zh: ["AI 之前"],
    tagline_en: "Works from my application journey.",
    tagline_zh: "申请季留下的作品。",
    desc_en: "My portfolio demonstrates how I went from studying industrial design to multidisciplinary training in interactive media. It's a record of an exploratory voyage that helped me decide what I wanted to concentrate on through my future studies — and through which I received offers from UCL, Edinburgh, and GSA.",
    desc_zh: "这套作品集记录了我从工业设计走向交互媒体多元训练的过程。它是一段探索之旅 —— 帮我确认接下来要专注的方向，也让我拿到了 UCL、爱丁堡和 GSA 的 offer。",
    tags_en: ["Industrial Design", "Speculative Design", "Interactive Media", "Performance Design", "5 Projects"],
    tags_zh: ["工业设计", "思辨设计", "交互媒体", "表演设计", "5 个项目"],
    heroImg: { label_en: "Industrial → Interaction", label_zh: "工业 → 交互", sub_en: "Portfolio Journey Map · ZC72", sub_zh: "作品集旅程图 · ZC72", tone: "mono-mist" },
    meta: [
      { label_en: "Era",         label_zh: "阶段",   value_en: "21 — 23 · Pre-MDes",                value_zh: "21 — 23 · 读硕前" },
      { label_en: "Discipline",  label_zh: "学科",   value_en: "Industrial Design → Interaction Design", value_zh: "工业设计 → 交互设计" },
      { label_en: "Outcome",     label_zh: "结果",   value_en: "Offers from UCL · Edinburgh · GSA ✓", value_zh: "拿到 UCL · 爱丁堡 · GSA ✓ 的 offer" },
      { label_en: "Format",      label_zh: "形式",   value_en: "5 projects · 24-page PDF",            value_zh: "5 个项目 · 24 页 PDF" },
    ],
    sections: [
      {
        type: "intro-block",
        label_en: "01 — Context",
        label_zh: "01 — 背景",
        title_en: "A snapshot just before AI made me rethink everything.",
        title_zh: "一段在 AI 让我重新思考一切之前的快照。",
        body_en: "A series of self-initiated projects developed during my transition from industrial design into interaction design. Presented in PDF format — a process of exploration and transformation before AI reshaped creative practice. Starting point: industrial design. Expected end point: design for performance & interaction. Achieved: GSA MDes Interaction Design.",
        body_zh: "我从工业设计转向交互设计期间的一组自发探索项目。以 PDF 形式呈现 —— 一段在 AI 重塑创作之前的探索与转变。起点：工业设计。预期终点：表演与交互的设计。实际结果：GSA 交互设计 MDes。",
      },
      {
        type: "archive-list",
        bg: "ink",
        label_en: "02 — Five Projects",
        label_zh: "02 — 五个项目",
        title_en: "Industrial Design → Performance & Interaction.",
        title_zh: "工业设计 → 表演与交互。",
        items: [
          {
            num: "01",
            title_en: "EASELBOW", title_zh: "EASELBOW",
            sub_en: "The Elbow Protection Product — For Assembly Line Workers",
            sub_zh: "工厂流水线工人的肘部防护产品",
            meta_en: "Industrial Design · IoT Wearable · 2022",
            meta_zh: "工业设计 · IoT 可穿戴 · 2022",
            body_en: "An imperceptible wearable integrated with work clothes — alerting and correcting workers' posture by vibrating or inflating. Focuses on Cubital Tunnel Syndrome (CBTS), a chronic ulnar nerve injury second only to carpal tunnel in incidence. A Piezoelectric-Film Sensor detects elbow compression angle; when bends exceed 90° for too long, it inflates or vibrates.",
            body_zh: "一件几乎无感的可穿戴产品，融入工作服 —— 通过震动或充气来提醒并矫正姿态。聚焦肘管综合征（CBTS），发病率仅次于腕管综合征。压电薄膜传感器检测肘部压迫角度；当弯曲超过 90° 持续过久时，会震动或充气示警。",
            tags_en: ["Arduino", "Piezoelectric Sensor", "Air Pump", "Occupational Health"],
            tags_zh: ["Arduino", "压电传感器", "气泵", "职业健康"],
          },
          {
            num: "02",
            title_en: "MIND BOX", title_zh: "MIND BOX",
            sub_en: "A Device to Trigger People to Consider the Influence of the Subconscious",
            sub_zh: "一个促人思考潜意识影响的装置",
            meta_en: "Speculative Design · Installation · 2022",
            meta_zh: "思辨设计 · 装置 · 2022",
            body_en: "What if different choices always lead to the same result? A speculative installation exploring the gap between subconscious and conscious decision-making. Drawing on Freud's Iceberg Theory (subconscious 95% / conscious 5%) and Eastern metaphysics (Numerology, BA-ZI, Tarot, Divination), MIND BOX materialises the philosophical question of free will.",
            body_zh: "如果不同的选择总会走向相同的结果？一个探索潜意识与意识决策之间裂缝的思辨装置。借鉴弗洛伊德的冰山理论（潜意识 95% / 意识 5%）与东方玄学（命理、八字、塔罗、占卜），MIND BOX 把「自由意志」这个哲学问题物质化。",
            tags_en: ["Speculative", "Freud's Iceberg", "Metaphysics", "Acrylic", "Installation"],
            tags_zh: ["思辨", "弗洛伊德冰山", "玄学", "亚克力", "装置"],
          },
          {
            num: "03",
            title_en: "Why I'm Passionate About Performance?", title_zh: "我为什么对表演如此热爱？",
            sub_en: "For Renewing Self And Love of Performance — Personal Narrative",
            sub_zh: "为了刷新自己、为了对表演的热爱 —— 个人叙事",
            meta_en: "Storytelling Design · Personal Essay · 2022",
            meta_zh: "叙事设计 · 个人随笔 · 2022",
            body_en: "Not a conventional project — a designed personal essay. It explains the through-line connecting all the work: why someone from industrial design keeps gravitating toward embodied experience, live performance, and emotion as design material. The conceptual spine of the entire application portfolio.",
            body_zh: "不是常规意义的项目，而是一份被「设计」过的个人随笔。它解释了贯穿所有作品的那条线：一个从工业设计出身的人，为什么始终被具身体验、现场表演、情绪作为设计材料所吸引。整个申请作品集的概念脊柱。",
            tags_en: ["Self-Identity", "Narrative Design", "Editorial", "Performance"],
            tags_zh: ["自我身份", "叙事设计", "编辑设计", "表演"],
          },
          {
            num: "04",
            title_en: "City Stage: The Extension of Body", title_zh: "城市舞台：身体的延伸",
            sub_en: "Connecting the Body and the City with Media Architecture",
            sub_zh: "用媒体建筑连接身体与城市",
            meta_en: "Interactive Architecture · Kinect · 2022",
            meta_zh: "交互建筑 · Kinect · 2022",
            body_en: "Using Kinect's real-time body-tracking, a two-scene performance. Verbal violence transforms into humanoid cage lines; digital emotional avatars split and merge — Anger (red), Fear (purple), Positivity (green), Sadness (blue) — evolving to gold as the body breaks free. Audience head-position shifts their 3D spatial perspective, making them co-performers.",
            body_zh: "基于 Kinect 的实时人体追踪，一场两幕的表演。语言暴力变成人形的笼线；数字情绪化身在分裂与合并 —— 愤怒（红）、恐惧（紫）、积极（绿）、悲伤（蓝） —— 在身体冲破束缚的瞬间转为金色。观众头部位置会改变 3D 空间视角，让他们成为共同表演者。",
            tags_en: ["Kinect", "3D Particle System", "Digital Avatar", "Live Performance"],
            tags_zh: ["Kinect", "3D 粒子系统", "数字化身", "现场表演"],
          },
          {
            num: "05",
            title_en: "Digital Imaging", title_zh: "数字影像",
            sub_en: "In the Interaction of Media, Architecture & The Experience of Body and City",
            sub_zh: "媒体、建筑与「身体与城市」的交互体验",
            meta_en: "Digital Image Creation · Interactive Media · 22—23",
            meta_zh: "数字影像创作 · 交互媒体 · 22—23",
            body_en: "Visual research and creative experiments exploring the intersection of body, city, and digital space. Served as preparation for City Stage — investigating how digital tools capture and transform the experience of embodied performance in urban environments.",
            body_zh: "视觉研究与创作实验，探索身体、城市与数字空间之间的交叠。作为 City Stage 的准备 —— 调查数字工具如何捕捉与转化城市环境中具身表演的体验。",
            tags_en: ["Digital Image", "Body & City", "Media Architecture"],
            tags_zh: ["数字影像", "身体与城市", "媒体建筑"],
          },
        ],
      },
    ],
    stats: [
      { num: "5",  label_en: "Projects archived",                                       label_zh: "5 个存档项目" },
      { num: "3",  label_en: "Offers received\nUCL · Edinburgh · GSA ✓",                label_zh: "3 个 offer\nUCL · 爱丁堡 · GSA ✓" },
      { num: "24", label_en: "PDF pages",                                                label_zh: "PDF 页数" },
      { num: "2",  label_en: "Years of exploration\nIndustrial → Interaction",          label_zh: "2 年探索\n工业 → 交互" },
    ],
    nextSlug: "luci-ai",
  },

};

export { PROJECTS };
